SELECT c.CUSTOMER_NAME, o.ORDER_ID, p.PRODUCT_NAME, o.ORDER_SELLING_PRICE
FROM RAW.GLOBALMART.customer c
JOIN RAW.GLOBALMART.orders o ON c.CUSTOMER_ID = o.CUSTOMER_ID
JOIN RAW.GLOBALMART.product p ON o.PRODUCT_ID = p.PRODUCT_ID;